### ISSUE TITLE
Unable to run the demo app

### ISSUE THREAD

**Issue by ipatka** [TeamAikon/ore-id-docs#82]
I am trying to run the demo app locally but getting an error on `npm run dev`

_Steps to reproduce_

Clone the repo

`cd examples/react/complete`

`npm install`

`npm run dev`

```
npm run dev

> react-sample-app@1.2.0 dev /PATH_TO/ore-id-docs/examples/react/complete
> react-scripts start


There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.42.0"
  ...
```

I ran `npm ls webpack` and got

```
react-sample-app@1.2.0 /PATH_TO/ore-id-docs/examples/react/complete
├─┬ oreid-js@2.13.2
│ └─┬ aikon-oreid-shared@1.2.7
│   └─┬ @open-rights-exchange/chainjs@3.1.4
│     └─┬ contract-proxy-kit@3.0.0
│       └─┬ @truffle/contract@4.3.29
│         └─┬ @ensdomains/ensjs@2.0.1
│           └─┬ @ensdomains/ens@0.4.3
│             └─┬ ethereumjs-testrpc@6.0.3
│               └── webpack@3.12.0
└─┬ react-scripts@3.4.1
  └── UNMET PEER DEPENDENCY webpack@4.42.0
  ```

**Comment by traylewin** [comment]
@ipatka we updated the dependancies. try it again now

**Comment by ipatka** [comment]
Different error

With `npm run dev`

I get

```
> react-scripts start

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack'
Require stack:
- /PATH/TO/ore-id-docs/examples/react/complete/node_modules/webpack-dev-server/lib/Server.js
- /PATH/TO/ore-id-docs/examples/react/complete/node_modules/react-scripts/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/PATH/TO/ore-id-docs/examples/react/complete/node_modules/webpack-dev-server/lib/Server.js:23:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/PATH/TO/ore-id-docs/examples/react/complete/node_modules/webpack-dev-server/lib/Server.js',
    '/PATH/TO/ore-id-docs/examples/react/complete/node_modules/react-scripts/scripts/start.js'
  ]
}
```
